#!/usr/bin/env bash
# PlangOS image build: Debian packages + self-contained plang -> sealed WSL rootfs tarball.
#
#   plangos/build.sh lock                 resolve packages.conf -> packages.lock (network)
#   plangos/build.sh image <plang-dir>    build out/plangos-amd64.tar.xz from packages.lock
#
# <plang-dir> is a `dotnet publish` of PlangConsole (linux-x64, self-contained) with the
# runtime's os/ folder copied in. See README.md for the exact publish command.
#
# How the rootfs is made (no container runtime, no root, no maintainer scripts):
#   1. every package in packages.lock is downloaded and checked against its sha256;
#   2. each non-denied .deb is unpacked with `dpkg-deb -x` into an empty root;
#   3. helper packages generate caches (ld.so.cache, fonts, GSettings) inside the root,
#      run through `unshare -r --root` (an unprivileged chroot), then are removed;
#   4. plang, /etc and /home/plang are added;
#   5. mktar.py writes a deterministic tarball: sorted, fixed owners, fixed mtimes,
#      and it refuses setuid/setgid files.
#
# Needs: bash, apt-get (lock only), dpkg-deb, curl, python3, xz, objdump (checks), util-linux unshare >= 2.36.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$HERE/packages.conf"
LOCK="$HERE/packages.lock"
KEYRING="$HERE/keys/debian-archive-keyring.gpg"
KEYRING_SHA256="506b815cbb32d9b6066b4a2aa524071e071761e7e7f68c3ac74f3061ba852017"
WORK="${PLANGOS_WORK:-$HERE/.work}"
OUT="${PLANGOS_OUT:-$HERE/out}"
ARCH=amd64

die() { echo "build.sh: $*" >&2; exit 1; }
log() { echo "==> $*" >&2; }

# packages.conf: "<key> <words...>  # comment"
conf() { sed -e 's/#.*//' "$CONF" | awk -v k="$1" '$1==k { for (i=2;i<=NF;i++) print $i }'; }

check_keyring() {
  echo "$KEYRING_SHA256  $KEYRING" | sha256sum -c --quiet - || die "keyring hash mismatch"
}

# ---------------------------------------------------------------------------------
# lock: resolve the closure from an EMPTY dpkg status against the pinned snapshot.
# ---------------------------------------------------------------------------------
apt_setup() {
  local snap suite A
  snap="$(conf snapshot)"; suite="$(conf suite)"
  A="$WORK/apt"
  rm -rf "$A"
  mkdir -p "$A"/etc/apt/{apt.conf.d,preferences.d,sources.list.d} "$A"/var/lib/dpkg \
           "$A"/var/lib/apt/lists/partial "$A"/var/cache/apt/archives/partial
  : > "$A/var/lib/dpkg/status"
  cat > "$A/etc/apt/sources.list" <<EOF
deb [signed-by=$KEYRING] http://snapshot.debian.org/archive/debian/$snap $suite main
deb [signed-by=$KEYRING] http://snapshot.debian.org/archive/debian/$snap $suite-updates main
deb [signed-by=$KEYRING] http://snapshot.debian.org/archive/debian-security/$snap $suite-security main
EOF
  cat > "$A/apt.conf" <<EOF
Dir "$A/";
Dir::State::status "$A/var/lib/dpkg/status";
APT::Architecture "$ARCH";
APT::Architectures { "$ARCH"; };
APT::Install-Recommends "false";
APT::Install-Suggests "false";
Acquire::Check-Valid-Until "false";
Acquire::Languages "none";
Debug::NoLocking "true";
EOF
  export APT_CONFIG="$A/apt.conf"
  apt-get update -qq
}

cmd_lock() {
  check_keyring
  apt_setup
  local roots helpers
  roots="$(conf root | tr '\n' ' ')"
  helpers="$(conf helper | tr '\n' ' ')"
  log "resolving: $roots + helpers: $helpers"
  # --print-uris gives the URL apt chose; the hash it prints depends on the apt
  # version (MD5 on older apt), so version + SHA256 come from apt-cache instead.
  # Output: "package version sha256 url"
  # shellcheck disable=SC2086
  apt-get install -qq --print-uris $roots $helpers \
    | sed -n "s/^'\([^']*\)' \([^_]*\)_.*/\2 \1/p" \
    | while read -r pkg url; do
        local file="${url##*/}"
        file="$(printf '%b' "${file//%/\\x}")"   # URL-decode (%2b, %7e, %3a)
        apt-cache show --no-all-versions "$pkg" | awk -v u="$file" -v url="$url" '
          /^Package:/ {p=$2} /^Version:/ {v=$2} /^SHA256:/ {s=$2}
          /^Filename:/ {n=split($2, a, "/"); f=a[n]}
          END {
            if (u != f) { print "mismatch " p ": " u " vs " f > "/dev/stderr"; exit 1 }
            print p, v, s, url
          }'
      done | LC_ALL=C sort > "$LOCK.tmp"
  [ -s "$LOCK.tmp" ] || die "resolution produced nothing"
  { echo "# generated by build.sh lock from packages.conf; snapshot $(conf snapshot)"
    echo "# package version sha256 url"
    cat "$LOCK.tmp"; } > "$LOCK"
  rm "$LOCK.tmp"
  log "wrote $(grep -vc '^#' "$LOCK") packages to packages.lock"
}

# ---------------------------------------------------------------------------------
# image
# ---------------------------------------------------------------------------------
fetch_debs() {
  local debs="$WORK/debs"
  mkdir -p "$debs"
  grep -v '^#' "$LOCK" | while read -r pkg ver sha url; do
    local f="$debs/${pkg}.deb"
    if [ ! -f "$f" ] || ! echo "$sha  $f" | sha256sum -c --quiet - 2>/dev/null; then
      curl -fsSL --retry 3 -o "$f.part" "$url"
      echo "$sha  $f.part" | sha256sum -c --quiet - || die "sha256 mismatch: $pkg"
      mv "$f.part" "$f"
    fi
  done
}

# Run a command inside the rootfs as an unprivileged chroot, with a clean environment.
in_root() { env -i PATH=/usr/bin:/usr/sbin unshare -r --root="$ROOT" "$@"; }

cmd_image() {
  local plang_dir="${1:-}"
  [ -n "$plang_dir" ] && [ -x "$plang_dir/plang" ] || die "usage: build.sh image <plang-publish-dir>"
  [ -d "$plang_dir/os/system" ] || die "$plang_dir/os/system missing: copy the runtime's os/ folder into the publish dir"
  [ -f "$LOCK" ] || die "packages.lock missing: run build.sh lock"

  export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git -C "$HERE" log -1 --format=%ct)}"
  ROOT="$WORK/rootfs"
  rm -rf "$ROOT"; mkdir -p "$ROOT" "$OUT"

  log "fetching packages"
  fetch_debs

  # merged /usr, as Debian trixie expects
  mkdir -p "$ROOT"/usr/{bin,sbin,lib,lib64}
  ln -s usr/bin "$ROOT/bin"; ln -s usr/sbin "$ROOT/sbin"
  ln -s usr/lib "$ROOT/lib"; ln -s usr/lib64 "$ROOT/lib64"

  local deny helper
  deny=" $(conf deny | tr '\n' ' ') "
  helper=" $(conf helper | tr '\n' ' ') "

  log "unpacking"
  : > "$WORK/unpacked.txt"
  grep -v '^#' "$LOCK" | while read -r pkg ver _ _; do
    case "$deny" in *" $pkg "*) continue ;; esac
    case "$helper" in *" $pkg "*) continue ;; esac
    dpkg-deb -x "$WORK/debs/$pkg.deb" "$ROOT"
    echo "$pkg $ver" >> "$WORK/unpacked.txt"
  done

  # dpkg status database, metadata only: PlangOS has no dpkg, but CVE scanners and SBOM
  # tools (grype, trivy, syft) find Debian packages through this file. Built from each
  # unpacked package's control file, in lock order, so it is deterministic.
  mkdir -p "$ROOT/var/lib/dpkg"
  : > "$ROOT/var/lib/dpkg/status"
  while read -r pkg _; do
    dpkg-deb -f "$WORK/debs/$pkg.deb" \
      | sed '/^Package:/a Status: install ok installed' >> "$ROOT/var/lib/dpkg/status"
    echo >> "$ROOT/var/lib/dpkg/status"
  done < "$WORK/unpacked.txt"

  log "generating caches with helpers"
  local h
  for h in $helper; do
    dpkg-deb -c "$WORK/debs/$h.deb" | awk '{print $6}' | sed 's|^\./|/|' > "$WORK/helper-$h.files"
    dpkg-deb -x "$WORK/debs/$h.deb" "$ROOT"
  done
  generate_caches
  for h in $helper; do
    # remove the helper's regular files and symlinks (never directories: they may be shared)
    while read -r f; do
      [ -n "$f" ] && [ "$f" != "/" ] || continue
      if [ -L "$ROOT$f" ] || [ -f "$ROOT$f" ]; then rm -f "$ROOT$f"; fi
    done < "$WORK/helper-$h.files"
  done

  log "trimming"
  trim

  log "adding plang and /etc"
  mkdir -p "$ROOT/opt/plang"
  cp -a "$plang_dir/." "$ROOT/opt/plang/"
  # PlangOS's display (the Wayland compositor Chromium draws into) is part of plang: the screen
  # module's Linux provider. Nothing else to add.
  find "$ROOT/opt/plang" -name '*.pdb' -delete
  # .NET's optional LTTng tracing provider: needs liblttng-ust, which PlangOS doesn't ship
  rm -f "$ROOT/opt/plang/libcoreclrtraceptprovider.so"
  cp -a "$HERE/rootfs/." "$ROOT/"
  : > "$ROOT/etc/fstab"
  ln -sf ../usr/share/zoneinfo/Etc/UTC "$ROOT/etc/localtime"
  echo "Etc/UTC" > "$ROOT/etc/timezone"
  mkdir -p "$ROOT/home/plang" "$ROOT/root" "$ROOT/tmp" "$ROOT/var/tmp" "$ROOT/run" \
           "$ROOT/proc" "$ROOT/sys" "$ROOT/dev"
  cp "$WORK/unpacked.txt" "$ROOT/opt/plang/os-packages.txt"

  local version="${PLANGOS_VERSION:-0.0.0-dev}"
  log "writing tarball (SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH)"
  python3 "$HERE/mktar.py" "$ROOT" "$OUT/plangos-$ARCH.tar"
  # Fast compression: the image is built and imported locally, so build time matters more than
  # file size (Ingi, 2026-09-28); -9 took most of the build. Multi-threaded xz output depends only
  # on the block size, never on the thread count, so the bytes are the same on any machine.
  xz -1 --threads=4 --block-size=64MiB -f "$OUT/plangos-$ARCH.tar"
  write_manifest "$version"
  log "done: $OUT/plangos-$ARCH.tar.xz"
}

generate_caches() {
  # ld.so.cache: Debian keeps some libraries in subdirectories (pulseaudio, ...)
  in_root /usr/sbin/ldconfig
  # aux-cache only speeds up the next ldconfig run and records inode numbers and
  # ctimes, so it differs on every build. Nothing reads it at runtime.
  rm -f "$ROOT/var/cache/ldconfig/aux-cache"
  # CA bundle: ca-certificates' postinst normally builds this with a shell script.
  mkdir -p "$ROOT/etc/ssl/certs"
  find "$ROOT/usr/share/ca-certificates" -name '*.crt' | LC_ALL=C sort | xargs cat \
    > "$ROOT/etc/ssl/certs/ca-certificates.crt"
  # GSettings schemas: GTK aborts at start without a compiled schema file.
  in_root /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
  # font cache, so Chromium's first start doesn't scan every font
  in_root /usr/bin/fc-cache -s -f
}

trim() {
  # documentation, manuals, lintian and bug-report metadata: never read at runtime
  rm -rf "$ROOT"/usr/share/{doc,man,info,lintian,bug,doc-base,menu,bash-completion}
  # the deny list keeps binaries out; also drop admin tools that came with libraries
  rm -rf "$ROOT"/usr/share/locale   # gettext translations of CLI tools we don't ship
  # Vulkan validation layer: a developer debugging aid (23 MB), never loaded unless asked for
  rm -f "$ROOT"/usr/lib/chromium/libVkLayer_khronos_validation.so "$ROOT"/usr/lib/chromium/VkLayer_khronos_validation.json
  # Mesa's GBM driver plugin: needs libgallium, which is denied (CPU rendering only)
  rm -rf "$ROOT"/usr/lib/x86_64-linux-gnu/gbm
  # shell scripts are dead weight without a shell: Debian's chromium launcher
  # (plang starts /usr/lib/chromium/chromium directly) and update-ca-certificates
  rm -f "$ROOT"/usr/bin/chromium "$ROOT"/usr/sbin/update-ca-certificates
}

write_manifest() {
  local version="$1" tgz="$OUT/plangos-$ARCH.tar.xz"
  python3 - "$tgz" "$version" "$(conf snapshot)" "$SOURCE_DATE_EPOCH" > "$OUT/manifest-$ARCH.json" <<'EOF'
import hashlib, json, os, sys
path, version, snapshot, epoch = sys.argv[1:]
h = hashlib.sha256()
with open(path, "rb") as f:
    for chunk in iter(lambda: f.read(1 << 20), b""):
        h.update(chunk)
print(json.dumps({
    "name": "PlangOS",
    "version": version,
    "arch": "amd64",
    "file": os.path.basename(path),
    "size": os.path.getsize(path),
    "sha256": h.hexdigest(),
    "debianSnapshot": snapshot,
    "sourceDateEpoch": int(epoch),
}, indent=2))
EOF
}

case "${1:-}" in
  lock)  cmd_lock ;;
  image) shift; cmd_image "$@" ;;
  *)     die "usage: build.sh lock | image <plang-publish-dir>" ;;
esac
